/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        aturAkses();
    }
    
    private void aturAkses() {
        if (Session.role.equals("pegawai")) {
            Master.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Master = new javax.swing.JMenu();
        Barang = new javax.swing.JMenuItem();
        Pelanggan = new javax.swing.JMenuItem();
        Suplier = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Pembelian = new javax.swing.JMenuItem();
        Penjualan = new javax.swing.JMenuItem();
        orderPembelian = new javax.swing.JMenuItem();
        orderPenjualan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM PEMBELIAN & PENJUALAN");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(88, 40));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(88, 40));

        Master.setText("Master");

        Barang.setText("Barang");
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });
        Master.add(Barang);

        Pelanggan.setText("Pelanggan");
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });
        Master.add(Pelanggan);

        Suplier.setText("Suplier");
        Suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuplierActionPerformed(evt);
            }
        });
        Master.add(Suplier);

        jMenuBar1.add(Master);

        Transaksi.setText("Transaksi");

        Pembelian.setText("Pembelian");
        Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembelianActionPerformed(evt);
            }
        });
        Transaksi.add(Pembelian);

        Penjualan.setText("Penjualan");
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        Transaksi.add(Penjualan);

        orderPembelian.setText("Order Pembelian");
        orderPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPembelianActionPerformed(evt);
            }
        });
        Transaksi.add(orderPembelian);

        orderPenjualan.setText("Order Penjualan");
        orderPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPenjualanActionPerformed(evt);
            }
        });
        Transaksi.add(orderPenjualan);

        jMenuBar1.add(Transaksi);

        jMenu3.setText("Laporan");

        Laporan.setText("Laporan");
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });
        jMenu3.add(Laporan);

        jMenuBar1.add(jMenu3);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        keluar.add(jMenuItem1);

        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(604, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
    new Transaksi.Penjualan().setVisible(true);        
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_PenjualanActionPerformed

    private void orderPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPenjualanActionPerformed
    new Transaksi.OrderPenjualan().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_orderPenjualanActionPerformed

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
    new Master.Barang().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_BarangActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
    new Master.Pelanggan().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_PelangganActionPerformed

    private void orderPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPembelianActionPerformed
    new Transaksi.OrderPembelian().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_orderPembelianActionPerformed

    private void SuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuplierActionPerformed
    new Master.Suplier().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_SuplierActionPerformed

    private void PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembelianActionPerformed
    new Transaksi.Pembelian().setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_PembelianActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
    new Laporan.Laporan().setVisible(true);        
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LaporanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    int res = JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Keluar?", "Konfirmasi", JOptionPane.YES_OPTION);
    if (res == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Barang;
    private javax.swing.JMenuItem Laporan;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuItem Pelanggan;
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenuItem Suplier;
    private javax.swing.JMenu Transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenuItem orderPembelian;
    private javax.swing.JMenuItem orderPenjualan;
    // End of variables declaration//GEN-END:variables
}
