/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Master;

import Koneksi.Koneksi;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class Barang extends javax.swing.JFrame {
private DefaultTableModel modelBarang;
private String selectedKode = "";

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        
        modelBarang = new DefaultTableModel(new Object[]{"Kode", "Nama", "Jumlah", "Harga Beli", "Harga Jual"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        tblBarang.setModel(modelBarang);
        loadBarang();
    }
    
    private void loadBarang() {
        modelBarang.setRowCount(0);
        
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT * FROM barang";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelBarang.addRow(new Object[] {
                   rs.getString("kode_barang"),
                   rs.getString("nama_barang"),
                   rs.getInt("jumlah"),
                   rs.getInt("harga_beli"),
                   rs.getInt("harga_jual"),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
        }
    }
    
    private void bersihForm() {
        txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtJumlahBarang.setText("");
        txtHargaBeli.setText("");
        txtHargaJual.setText("");
        selectedKode = "";
        tblBarang.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblKodeBarang = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        lblJumlahBarang = new javax.swing.JLabel();
        lblHargaBeli = new javax.swing.JLabel();
        txtJumlahBarang = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        lblHargaJual = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblKodeBarang1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnEdit1 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Master Form Barang");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        lblKodeBarang.setText("Kode Barang");

        lblNamaBarang.setText("Nama Barang");

        lblJumlahBarang.setText("Jumlah Barang");

        lblHargaBeli.setText("Harga Beli");

        lblHargaJual.setText("Harga Jual");

        btnCari.setText("Cari");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus1.setText("Hapus");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnClear.setText("Kosongkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblKodeBarang1.setText("Search");

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lblKodeBarang)
                        .addGap(333, 333, 333)
                        .addComponent(lblKodeBarang1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamaBarang)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJumlahBarang)
                            .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHargaBeli)
                            .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHargaJual)
                            .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKodeBarang)
                    .addComponent(lblKodeBarang1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNamaBarang)
                        .addGap(14, 14, 14)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblJumlahBarang)
                        .addGap(14, 14, 14)
                        .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblHargaBeli)
                        .addGap(14, 14, 14)
                        .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblHargaJual)
                        .addGap(14, 14, 14)
                        .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
    if ("".equals(selectedKode)) {
        JOptionPane.showMessageDialog(this, "Pilih Barang!");
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus?");
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection conn = Koneksi.getConnection();
            String sqlHapus = "DELETE FROM barang WHERE kode_barang=?";
            PreparedStatement ps = conn.prepareStatement(sqlHapus);
            ps.setString(1, selectedKode);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Hapus!");
            bersihForm();
            loadBarang();
            conn.close();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     if (
             txtKodeBarang.getText().isEmpty() ||
             txtNamaBarang.getText().isEmpty() || 
             txtJumlahBarang.getText().isEmpty() || 
             txtHargaBeli.getText().isEmpty() || 
             txtHargaJual.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Field Harus Diisi!");
     }
     
     if (Integer.parseInt(txtJumlahBarang.getText()) < 0 || Integer.parseInt(txtHargaBeli.getText()) < 0 || Integer.parseInt(txtHargaJual.getText()) < 0) {
         JOptionPane.showMessageDialog(this, "Numerik tidak boleh Negatif!");
         return;
     }
     
     try {
         Connection conn = Koneksi.getConnection();
         String sqlTambah = "INSERT INTO barang (kode_barang, nama_barang, jumlah, harga_beli, harga_jual) VALUES (?, ?, ?, ?, ?)";
         PreparedStatement ps = conn.prepareStatement(sqlTambah);
         ps.setString(1, txtKodeBarang.getText());
         ps.setString(2, txtNamaBarang.getText());
         ps.setInt(3, Integer.parseInt(txtJumlahBarang.getText()));
         ps.setInt(4, Integer.parseInt(txtHargaBeli.getText()));
         ps.setInt(5, Integer.parseInt(txtHargaJual.getText()));
         ps.executeUpdate();
         JOptionPane.showMessageDialog(this, "Berhasil Tambah");
         loadBarang();
         bersihForm();
         conn.close();
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
     }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
     int row = tblBarang.getSelectedRow();
     
     selectedKode = modelBarang.getValueAt(row, 0).toString();
     txtKodeBarang.setText(selectedKode);
     txtNamaBarang.setText(modelBarang.getValueAt(row, 1).toString());
     txtJumlahBarang.setText(modelBarang.getValueAt(row, 2).toString());
     txtHargaBeli.setText(modelBarang.getValueAt(row, 3).toString());
     txtHargaJual.setText(modelBarang.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    bersihForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
         if (
             txtKodeBarang.getText().isEmpty() ||
             txtNamaBarang.getText().isEmpty() || 
             txtJumlahBarang.getText().isEmpty() || 
             txtHargaBeli.getText().isEmpty() || 
             txtHargaJual.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Field Harus Diisi!");
     }
         if (
                 Integer.parseInt(txtJumlahBarang.getText()) < 0 || 
                 Integer.parseInt(txtHargaBeli.getText()) < 0 || 
                 Integer.parseInt(txtHargaJual.getText()) < 0) {
         JOptionPane.showMessageDialog(this, "Numerik tidak boleh Negatif!");
         return; 
         }
         
         try {
             Connection conn = Koneksi.getConnection();
             String sqlEdit = "UPDATE barang SET nama_barang=?, jumlah=?, harga_beli=?, harga_jual=? WHERE kode_barang=?";
             PreparedStatement ps = conn.prepareStatement(sqlEdit);
             ps.setString(1, txtNamaBarang.getText());
             ps.setInt(2, Integer.parseInt(txtJumlahBarang.getText()));
             ps.setInt(3, Integer.parseInt(txtHargaBeli.getText()));
             ps.setInt(4, Integer.parseInt(txtHargaJual.getText()));
             ps.setString(5, txtKodeBarang.getText());
             ps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Berhasil Update!");
             loadBarang();
             bersihForm();
             conn.close();
         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error Edit : " + e.getMessage());
         }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnTambah;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHargaBeli;
    private javax.swing.JLabel lblHargaJual;
    private javax.swing.JLabel lblJumlahBarang;
    private javax.swing.JLabel lblKodeBarang;
    private javax.swing.JLabel lblKodeBarang1;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
